import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/widgets/boxy_art_widgets.dart';
import '../../../../models/season.dart';
import '../../../events/presentation/events_provider.dart';

import '../../../../core/theme/contrast_helper.dart';

class AdminSeasonsScreen extends ConsumerWidget {
  const AdminSeasonsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final seasonsAsync = ref.watch(seasonsProvider);
    final primaryColor = Theme.of(context).primaryColor;
    final onPrimary = ContrastHelper.getContrastingText(primaryColor);

    return Scaffold(
      appBar: BoxyArtAppBar(
        title: 'Manage Seasons', 
        isLarge: true,
        leadingWidth: 70,
        leading: Center(
          child: TextButton(
            onPressed: () => context.pop(),
            child: Text('Back', style: TextStyle(color: onPrimary, fontWeight: FontWeight.bold)),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddSeasonDialog(context, ref),
        child: const Icon(Icons.add),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const BoxyArtSectionTitle(
            title: 'Seasons Manager',
            padding: EdgeInsets.fromLTRB(24, 24, 24, 8),
          ),
          Expanded(
            child: seasonsAsync.when(
              data: (seasons) {
                if (seasons.isEmpty) {
                  return const Center(child: Text('No seasons created yet.'));
                }
                return ListView.separated(
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 8),
                  itemCount: seasons.length,
                  separatorBuilder: (context, index) => const SizedBox(height: 16),
                  itemBuilder: (context, index) {
                    final season = seasons[index];
                    return _SeasonCard(season: season);
                  },
                );
              },
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (err, stack) => Center(child: Text('Error: $err')),
            ),
          ),
        ],
      ),
    );
  }

  void _showAddSeasonDialog(BuildContext context, WidgetRef ref) {
    final nameController = TextEditingController();
    final yearController = TextEditingController(text: DateTime.now().year.toString());

    showBoxyArtDialog(
      context: context,
      title: 'New Season',
      message: 'Create a new season to group your events.',
      onConfirm: () async {
        if (nameController.text.isEmpty) return;
        final year = int.tryParse(yearController.text) ?? DateTime.now().year;
        
        final newSeason = Season(
          id: '', // Generated by Firestore
          name: nameController.text,
          year: year,
          status: SeasonStatus.active,
        );

        await ref.read(seasonsRepositoryProvider).addSeason(newSeason);
        if (context.mounted) Navigator.of(context, rootNavigator: true).pop();
      },
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          TextField(
            controller: nameController,
            decoration: const InputDecoration(labelText: 'Season Name (e.g. 2025 Tour)'),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: yearController,
            decoration: const InputDecoration(labelText: 'Year'),
            keyboardType: TextInputType.number,
          ),
        ],
      ),
    );
  }
}

class _SeasonCard extends ConsumerWidget {
  final Season season;
  const _SeasonCard({required this.season});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isActive = season.status == SeasonStatus.active;

    return BoxyArtFloatingCard(
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: isActive ? Colors.green.withValues(alpha: 0.1) : Colors.grey.withValues(alpha: 0.1),
              shape: BoxShape.circle,
            ),
            child: Icon(
              isActive ? Icons.play_arrow : Icons.archive,
              color: isActive ? Colors.green : Colors.grey,
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Text(
                      season.name,
                      style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                    ),
                    if (season.isCurrent) ...[
                      const SizedBox(width: 8),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: Theme.of(context).colorScheme.primary,
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: const Text(
                          'CURRENT',
                          style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ],
                  ],
                ),
                Text(
                  'Year: ${season.year} • ${season.status.name.toUpperCase()}',
                  style: const TextStyle(fontSize: 12, color: Colors.grey),
                ),
              ],
            ),
          ),
          if (isActive)
            Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                if (!season.isCurrent)
                  TextButton(
                    onPressed: () => ref.read(seasonsRepositoryProvider).setCurrentSeason(season.id),
                    style: TextButton.styleFrom(
                      padding: const EdgeInsets.symmetric(horizontal: 8),
                      minimumSize: Size.zero,
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                    ),
                    child: const Text('Make Current', style: TextStyle(fontSize: 11)),
                  ),
                IconButton(
                  onPressed: () => _showCloseSeasonDialog(context, ref),
                  padding: EdgeInsets.zero,
                  constraints: const BoxConstraints(),
                  icon: const Icon(Icons.archive_outlined, color: Colors.red, size: 20),
                  tooltip: 'Close Season',
                ),
              ],
            ),
        ],
      ),
    );
  }

  void _showCloseSeasonDialog(BuildContext context, WidgetRef ref) {
    // In a real app, we'd prompt for AGM results here.
    // For this prototype, we'll just close it.
    showBoxyArtDialog(
      context: context,
      title: 'Close Season?',
      message: 'This will move the season and all its events to the Archive. This cannot be undone.',
      onConfirm: () async {
        await ref.read(seasonsRepositoryProvider).closeSeason(season.id, {
          'captain': 'TBD',
          'playerOfTheYear': 'TBD',
          'majorWinners': [],
        });
        if (context.mounted) Navigator.of(context, rootNavigator: true).pop();
      },
      confirmText: 'Close & Archive',
    );
  }
}
