
final List<Map<String, String>> countryList = [
  {'code': '+93', 'flag': '🇦🇫', 'name': 'Afghanistan'},
  {'code': '+355', 'flag': '🇦🇱', 'name': 'Albania'},
  {'code': '+213', 'flag': '🇩🇿', 'name': 'Algeria'},
  {'code': '+376', 'flag': '🇦🇩', 'name': 'Andorra'},
  {'code': '+244', 'flag': '🇦🇴', 'name': 'Angola'},
  {'code': '+54', 'flag': '🇦🇷', 'name': 'Argentina'},
  {'code': '+374', 'flag': '🇦🇲', 'name': 'Armenia'},
  {'code': '+61', 'flag': '🇦🇺', 'name': 'Australia'},
  {'code': '+43', 'flag': '🇦🇹', 'name': 'Austria'},
  {'code': '+994', 'flag': '🇦🇿', 'name': 'Azerbaijan'},
  {'code': '+973', 'flag': '🇧🇭', 'name': 'Bahrain'},
  {'code': '+880', 'flag': '🇧🇩', 'name': 'Bangladesh'},
  {'code': '+375', 'flag': '🇧🇾', 'name': 'Belarus'},
  {'code': '+32', 'flag': '🇧🇪', 'name': 'Belgium'},
  {'code': '+501', 'flag': '🇧🇿', 'name': 'Belize'},
  {'code': '+229', 'flag': '🇧🇯', 'name': 'Benin'},
  {'code': '+975', 'flag': '🇧🇹', 'name': 'Bhutan'},
  {'code': '+591', 'flag': '🇧🇴', 'name': 'Bolivia'},
  {'code': '+387', 'flag': '🇧🇦', 'name': 'Bosnia'},
  {'code': '+267', 'flag': '🇧🇼', 'name': 'Botswana'},
  {'code': '+55', 'flag': '🇧🇷', 'name': 'Brazil'},
  {'code': '+673', 'flag': '🇧🇳', 'name': 'Brunei'},
  {'code': '+359', 'flag': '🇧🇬', 'name': 'Bulgaria'},
  {'code': '+226', 'flag': '🇧🇫', 'name': 'Burkina Faso'},
  {'code': '+257', 'flag': '🇧🇮', 'name': 'Burundi'},
  {'code': '+855', 'flag': '🇰🇭', 'name': 'Cambodia'},
  {'code': '+237', 'flag': '🇨🇲', 'name': 'Cameroon'},
  {'code': '+1', 'flag': '🇨🇦', 'name': 'Canada'},
  {'code': '+56', 'flag': '🇨🇱', 'name': 'Chile'},
  {'code': '+86', 'flag': '🇨🇳', 'name': 'China'},
  {'code': '+57', 'flag': '🇨🇴', 'name': 'Colombia'},
  {'code': '+506', 'flag': '🇨🇷', 'name': 'Costa Rica'},
  {'code': '+385', 'flag': '🇭🇷', 'name': 'Croatia'},
  {'code': '+53', 'flag': '🇨🇺', 'name': 'Cuba'},
  {'code': '+357', 'flag': '🇨🇾', 'name': 'Cyprus'},
  {'code': '+420', 'flag': '🇨🇿', 'name': 'Czech Republic'},
  {'code': '+45', 'flag': '🇩🇰', 'name': 'Denmark'},
  {'code': '+593', 'flag': '🇪🇨', 'name': 'Ecuador'},
  {'code': '+20', 'flag': '🇪🇬', 'name': 'Egypt'},
  {'code': '+372', 'flag': '🇪🇪', 'name': 'Estonia'},
  {'code': '+251', 'flag': '🇪🇹', 'name': 'Ethiopia'},
  {'code': '+358', 'flag': '🇫🇮', 'name': 'Finland'},
  {'code': '+33', 'flag': '🇫🇷', 'name': 'France'},
  {'code': '+995', 'flag': '🇬🇪', 'name': 'Georgia'},
  {'code': '+49', 'flag': '🇩🇪', 'name': 'Germany'},
  {'code': '+233', 'flag': '🇬🇭', 'name': 'Ghana'},
  {'code': '+30', 'flag': '🇬🇷', 'name': 'Greece'},
  {'code': '+502', 'flag': '🇬🇹', 'name': 'Guatemala'},
  {'code': '+852', 'flag': '🇭🇰', 'name': 'Hong Kong'},
  {'code': '+36', 'flag': '🇭🇺', 'name': 'Hungary'},
  {'code': '+354', 'flag': '🇮🇸', 'name': 'Iceland'},
  {'code': '+91', 'flag': '🇮🇳', 'name': 'India'},
  {'code': '+62', 'flag': '🇮🇩', 'name': 'Indonesia'},
  {'code': '+98', 'flag': '🇮🇷', 'name': 'Iran'},
  {'code': '+964', 'flag': '🇮🇶', 'name': 'Iraq'},
  {'code': '+353', 'flag': '🇮🇪', 'name': 'Ireland'},
  {'code': '+972', 'flag': '🇮🇱', 'name': 'Israel'},
  {'code': '+39', 'flag': '🇮🇹', 'name': 'Italy'},
  {'code': '+81', 'flag': '🇯🇵', 'name': 'Japan'},
  {'code': '+962', 'flag': '🇯🇴', 'name': 'Jordan'},
  {'code': '+7', 'flag': '🇰🇿', 'name': 'Kazakhstan'},
  {'code': '+254', 'flag': '🇰🇪', 'name': 'Kenya'},
  {'code': '+965', 'flag': '🇰🇼', 'name': 'Kuwait'},
  {'code': '+371', 'flag': '🇱🇻', 'name': 'Latvia'},
  {'code': '+961', 'flag': '🇱🇧', 'name': 'Lebanon'},
  {'code': '+370', 'flag': '🇱🇹', 'name': 'Lithuania'},
  {'code': '+352', 'flag': '🇱🇺', 'name': 'Luxembourg'},
  {'code': '+60', 'flag': '🇲🇾', 'name': 'Malaysia'},
  {'code': '+960', 'flag': '🇲🇻', 'name': 'Maldives'},
  {'code': '+356', 'flag': '🇲🇹', 'name': 'Malta'},
  {'code': '+52', 'flag': '🇲🇽', 'name': 'Mexico'},
  {'code': '+377', 'flag': '🇲🇨', 'name': 'Monaco'},
  {'code': '+212', 'flag': '🇲🇦', 'name': 'Morocco'},
  {'code': '+95', 'flag': '🇲🇲', 'name': 'Myanmar'},
  {'code': '+977', 'flag': '🇳🇵', 'name': 'Nepal'},
  {'code': '+31', 'flag': '🇳🇱', 'name': 'Netherlands'},
  {'code': '+64', 'flag': '🇳🇿', 'name': 'New Zealand'},
  {'code': '+234', 'flag': '🇳🇬', 'name': 'Nigeria'},
  {'code': '+47', 'flag': '🇳🇴', 'name': 'Norway'},
  {'code': '+968', 'flag': '🇴🇲', 'name': 'Oman'},
  {'code': '+92', 'flag': '🇵🇰', 'name': 'Pakistan'},
  {'code': '+507', 'flag': '🇵🇦', 'name': 'Panama'},
  {'code': '+51', 'flag': '🇵🇪', 'name': 'Peru'},
  {'code': '+63', 'flag': '🇵🇭', 'name': 'Philippines'},
  {'code': '+48', 'flag': '🇵🇱', 'name': 'Poland'},
  {'code': '+351', 'flag': '🇵🇹', 'name': 'Portugal'},
  {'code': '+974', 'flag': '🇶🇦', 'name': 'Qatar'},
  {'code': '+40', 'flag': '🇷🇴', 'name': 'Romania'},
  {'code': '+7', 'flag': '🇷🇺', 'name': 'Russia'},
  {'code': '+966', 'flag': '🇸🇦', 'name': 'Saudi Arabia'},
  {'code': '+221', 'flag': '🇸🇳', 'name': 'Senegal'},
  {'code': '+381', 'flag': '🇷🇸', 'name': 'Serbia'},
  {'code': '+65', 'flag': '🇸🇬', 'name': 'Singapore'},
  {'code': '+421', 'flag': '🇸🇰', 'name': 'Slovakia'},
  {'code': '+386', 'flag': '🇸🇮', 'name': 'Slovenia'},
  {'code': '+27', 'flag': '🇿🇦', 'name': 'South Africa'},
  {'code': '+82', 'flag': '🇰🇷', 'name': 'South Korea'},
  {'code': '+34', 'flag': '🇪🇸', 'name': 'Spain'},
  {'code': '+94', 'flag': '🇱🇰', 'name': 'Sri Lanka'},
  {'code': '+46', 'flag': '🇸🇪', 'name': 'Sweden'},
  {'code': '+41', 'flag': '🇨🇭', 'name': 'Switzerland'},
  {'code': '+886', 'flag': '🇹🇼', 'name': 'Taiwan'},
  {'code': '+66', 'flag': '🇹🇭', 'name': 'Thailand'},
  {'code': '+90', 'flag': '🇹🇷', 'name': 'Turkey'},
  {'code': '+971', 'flag': '🇦🇪', 'name': 'UAE'},
  {'code': '+256', 'flag': '🇺🇬', 'name': 'Uganda'},
  {'code': '+380', 'flag': '🇺🇦', 'name': 'Ukraine'},
  {'code': '+44', 'flag': '🇬🇧', 'name': 'United Kingdom'},
  {'code': '+1', 'flag': '🇺🇸', 'name': 'United States'},
  {'code': '+598', 'flag': '🇺🇾', 'name': 'Uruguay'},
  {'code': '+58', 'flag': '🇻🇪', 'name': 'Venezuela'},
  {'code': '+84', 'flag': '🇻🇳', 'name': 'Vietnam'},
  {'code': '+967', 'flag': '🇾🇪', 'name': 'Yemen'},
  {'code': '+260', 'flag': '🇿🇲', 'name': 'Zambia'},
  {'code': '+263', 'flag': '🇿🇼', 'name': 'Zimbabwe'},
];
